# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SJTU(object):
    def setupUi(self, SJTU):
        SJTU.setObjectName("SJTU")
        SJTU.resize(643, 378)
        self.pushButton123 = QtWidgets.QPushButton(SJTU)
        self.pushButton123.setGeometry(QtCore.QRect(250, 30, 161, 31))
        self.pushButton123.setObjectName("pushButton123")
        self.pushButton = QtWidgets.QPushButton(SJTU)
        self.pushButton.setGeometry(QtCore.QRect(130, 330, 181, 23))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(SJTU)
        self.textEdit.setGeometry(QtCore.QRect(110, 270, 441, 41))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(SJTU)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 330, 181, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(SJTU)
        self.pushButton.clicked.connect(SJTU.get_query) # type: ignore
        self.pushButton_2.clicked.connect(SJTU.get_bool) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SJTU)

    def retranslateUi(self, SJTU):
        _translate = QtCore.QCoreApplication.translate
        SJTU.setWindowTitle(_translate("SJTU", "SJTU"))
        self.pushButton123.setText(_translate("SJTU", "SJTU-NewsSearch"))
        self.pushButton.setText(_translate("SJTU", "Search"))
        self.textEdit.setHtml(_translate("SJTU", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_2.setText(_translate("SJTU", "Boolean Search"))
